name: Lean Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Elan
        run: |
          curl -sSf https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | sh -s -- -y --default-toolchain leanprover/lean4:v4.15.0
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
          echo "$HOME/.elan/bin" >> $HOME/.profile
      
      - name: Lake update
        run: |
          ~/.elan/bin/lake update
          
      - name: Lake build
        run: |
          ~/.elan/bin/lake build
