name: Lean Build -- Clean Proofs
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Elan
        run: |
          curl -sSf https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | sh -s -- -y --default-toolchain leanprover/lean4:v4.15.0
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - name: Lake update
        run: lake update
      - name: Build all (Build 93 CLEAN)
        run: lake build
